field.formatter.third_party.fences:
  type: mapping
  label: 'Fences configuration'
  mapping:
    fences_field_tag:
      type: string
      label: 'The field HTML tag'
    fences_field_classes:
      type: string
      label: 'The field CSS classes'
    fences_field_items_wrapper_tag:
      type: string
      label: 'The field items wrapper HTML tag'
    fences_field_items_wrapper_classes:
      type: string
      label: 'The field items wrapper CSS classes'
    fences_field_item_tag:
      type: string
      label: 'The field item HTML tag'
    fences_field_item_classes:
      type: string
      label: 'The field item CSS classes'
    fences_label_tag:
      type: string
      label: 'The field label HTML tag'
    fences_label_classes:
      type: string
      label: 'The field label CSS classes'
